---
groups:
- name: default
  jobs:
  - deploy

jobs:
- name: deploy
  serial: true
  plan:
  - get: app
  - task: deploy
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          version: xenial
      params:
        KUBECONFIG_CONTENTS: ((kubeconfig))
        YTT_key__nested: "foo"
      inputs:
        - name: app
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -e -x
          apt-get -y update
          apt-get -y install wget

          dst_dir="${K14SIO_INSTALL_BIN_DIR:-/usr/local/bin}"
          echo "Installing kapp..."
          wget -O- https://github.com/k14s/kapp/releases/download/v0.11.0/kapp-linux-amd64 > /tmp/kapp
          mv /tmp/kapp ${dst_dir}/kapp
          chmod +x ${dst_dir}/kapp
          echo "Installed ${dst_dir}/kapp"

          mkdir -p ~/.kube
          set +x
          echo "$KUBECONFIG_CONTENTS" > ~/.kube/config
          set -x

          echo $KUBECONFIG_CONTENTS
          kapp deploy -a app -f app/config/ -c -y

resources:
- name: app
  type: git
  source:
    uri: https://github.com/mayureshkrishna/k8s-pipeline.git
    branch: master